
jwt:
  secret : ekqpreuorqiueriqeurpeqruqoruoqure



server:
  port: 8080
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_pro?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
